### ISSUE TITLE
棋譜を保存できる

### ISSUE THREAD

**Issue by st34-satoshi** [st34-satoshi/chess-results#1]
data/ex/2024-01-01.csv にpgn_movesを追加して、データベースにtextで保存する。
すでに対局データを保存しているので
`docker compose exec web rake database:add_pgn_moves` で既存のデータベースに棋譜を上書きするのが良さそう。

pgn_movesには
`1. e4 c6 2. Nf3 d5 `
みたいな文字列が入る

**Comment by grkon03** [comment]
csv の情報からゲームを一意に特定する方法がないので、
同じ日に、同じプレイヤーの組み合わせが、同じ色でゲームをすることはない
という仮定でゲームを特定することにします。
条件が緩かったり、その他問題があったりすれば、指摘していただきたいです。

**Comment by st34-satoshi** [comment]
はい、それでお願いします。
現在表示はしていませんが、大会名も保存しています(csvではSourceでDBではtournaments.name)。
余裕があれば、同じ日に、**同じ大会で**、同じプレイヤーの組み合わせが、同じ色でゲームをすることはない、にした方が良いかもです。

Railsの説明をしてなくてどこまでご存知か分かりませんが、DBのテーブルにカラムを追加するときは
`docker compose exec web rails generate migration AddPGNMovesToGames pgn_moves:text`
みたいな感じでできます。
「rails カラム 追加」とかで調べると出てくると思います。

**Comment by grkon03** [comment]
承知しました。ありがとうございます。
